version: "3"
services: 
  node-app :
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - modules:/app/node_modules
    command: npm run dev
volumes:
  modules: