version: "3"
services:
  nginx:
    deploy:
      restart_policy:
        condition: any
  node-app :
    deploy:
      replicas: 6
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
        failure_action: rollback
    build: 
      context: .
      args: 
        NODE_ENV: production
    command: >
      /bin/sh -c "npm run build && npm run start"