version: "3"
services: 
  node-app :
    build: .
    ports: 
      - "5000:3000"
    env_file: 
      - ./.env
  postgres:
    image: postgres:13.3-alpine
    env_file: 
      - ./.env
    volumes: 
      - pgdata:/var/lib/postgresql/data
volumes: 
  pgdata:
